### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by Mte90** [BGMP/firefox-revert-proton#1]
I am looking for an alternative UI in firefox with proton to be more compact but there is no screenshot about how those rules change Firefox itself.
It is possible to add them?

**Comment by intrnl** [comment]
You mean like, a screenshot of what this userChrome.css does?

**Comment by Mte90** [comment]
Yes!

**Comment by intrnl** [comment]
I haven't used Firefox for almost a week now so I'm not sure how much Mozilla has changed the UI around since the last time I committed, but here's a screenshot of what it should look like.

![unknown-5](https://user-images.githubusercontent.com/20620901/115565575-b00f4a00-a2e3-11eb-812b-120f14b2f1e3.png)

Luckily, [someone already published a theme using the previous color scheme](https://addons.mozilla.org/en-US/firefox/addon/photon-dark/).

I decided to wait around until Mozilla is done with what they're doing because it seems like they're going to do additional cleanup down the line.

**Comment by Mte90** [comment]
So I get the same UI before proton? wow I will try it :-)

**Comment by BGMP** [comment]
Please keep up with the project! I almost threw up with the new proton design. If this brings back the old firefox you might wanna add a sponsors button for me to punch.

~~I noticed that the tabs are a little smaller than in the 88.0 release... is that intentional?~~ nvm, I'm an idiot, I didn't read it said compact. That said, though, any plans on adapting it for the normal version of Photon? That's the one I used to have.

**Comment by intrnl** [comment]
Sorry for not noticing the issue, but no, I have no plans for the regular mode. I see that you've forked it though, so please keep it up!

**Comment by intrnl** [comment]
I'm going to close the issue now :wave:
